In [1]:
# my imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Example DataFrame
data = pd.read_csv('data/reviews_with_predicted_v_given_sentiment.csv')

In [5]:
data.head()

,#,book_name,reviewer_anonymous,reviewer_rating,review_description,date,sentiment_given,sentiment_predicted
0,0,The Woman in Me,6ce3606d5be9785bcd9b10b844b98cf3b337b7a97a7f9c...,4,I'm only a third way in. Shipped lightening fa...,26-10-2023,positive,positive
1,1,The Woman in Me,243aa726ab7df2a7630a3a36c7d3a12f14e9d80cd3ab83...,5,"""There have been so many times when I was scar...",06-11-2023,positive,positive
2,2,The Woman in Me,eaea2ab37288945d63173beddf5680a39c37672c4386d6...,5,The media could not be loaded. I personally ha...,01-11-2023,positive,positive
3,3,The Woman in Me,9e554d1ebb53e03ec42b99ae5842c8a7309af90010bc51...,5,I have been a fan of Britney's music since the...,25-10-2023,positive,positive
4,4,The Woman in Me,4795e19c3660f232dd519252ac99d99fd53e23c7cf9a5e...,5,"Whether or not you’re a fan, it’s a great read...",01-11-2023,positive,positive

In [6]:
# Step 1: Filter to include only positive reviews
positive_reviews = data[data['sentiment_given'] == 'positive']

In [8]:
# Step 2: Group by title to get the count of positive reviews per book
positive_count = positive_reviews.groupby('book_name').size().reset_index(name='positive_count')

In [9]:
# Step 3: Group the entire dataset by title to get the total count of reviews per book
total_count = data.groupby('book_name').size().reset_index(name='total_count')

In [11]:
# Step 4: Merge the positive count and total count DataFrames
merged_df = pd.merge(positive_count, total_count, on='book_name')

In [14]:
# Step 5: Calculate the percentage of positive reviews
merged_df['positive_percentage'] = (merged_df['positive_count'] / merged_df['total_count']) * 100

# Display the result
merged_df.describe().T

,count,mean,std,min,25%,50%,75%,max
positive_count,91.0,9.945055,1.177216,7.0,10.0,10.0,10.0,20.0
total_count,91.0,10.076923,1.097783,7.0,10.0,10.0,10.0,20.0
positive_percentage,91.0,98.681319,4.002441,80.0,100.0,100.0,100.0,100.0

In [21]:
merged_df.book_name.unique()

array(['A Court of Mist and Fury (A Court of Thorns and Roses, 2)',
       'A Court of Thorns and Roses (A Court of Thorns and Roses, 1)',
       'A Court of Thorns and Roses Paperback Box Set (5 books)',
       'A Court of Wings and Ruin (A Court of Thorns and Roses, 3)',
       'A Little Life', 'All the Light We Cannot See: A Novel',
       'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
       "Balloons over Broadway: The True Story of the Puppeteer of Macy's Parade (Bank Street College of Education Flora Stieglitz Straus Award (Awards))",
       'Brown Bear, Brown Bear, What Do You See?',
       'Chicka Chicka Boom Boom (Board Book)',
       'Demon Copperhead: A Pulitzer Prize Winner',
       'Dirty Thirty (30) (Stephanie Plum)',
       "Don't Let the Pigeon Drive the Sleigh!", 'Elon Musk',
       'First Little Readers Parent Pack: Guided Reading Level A: 25 Irresistible Books That Are Just the Right Level for Beginning Readers',
       'Five Silly Turkeys', 'Flash Cards: Sight Words',
       'Forever Strong: A New, Science-Based Strategy for Aging Well',
       'Fourth Wing (The Empyrean, 1)',
       'Friends, Lovers, and the Big Terrible Thing: A Memoir',
       "From Crook to Cook: Platinum Recipes from Tha Boss Dogg's Kitchen (Snoop Dogg Cookbook, Celebrity Cookbook with Soul Food Recipes) (Snoop Dog x Chronicle Books)",
       'Goodnight Moon',
       "Goodnight, Goodnight Construction Site (Board Book for Toddlers, Children's Board Book)",
       'Harry Potter Paperback Box Set (Books 1-7)',
       'Harry Potter and the Prisoner of Azkaban (Harry Potter, Book 3) (MinaLima Edition)',
       'Hatchet', 'Haunting Adeline (Cat and Mouse Duet)',
       'Hello, Baby Animals: A Durable High-Contrast Black-and-White Board Book for Newborns and Babies (High-Contrast Books)',
       'Hidden Potential: The Science of Achieving Greater Things',
       'How to Catch a Dinosaur', 'How to Catch a Reindeer',
       'How to Catch a Turkey', 'How to Catch an Elf',
       'How to Know a Person: The Art of Seeing Others Deeply and Being Deeply Seen',
       "Hundred Years' War on Palestine",
       'I Am Thankful: A Thanksgiving Book for Kids',
       'I Love You Like No Otter: A Funny and Sweet Animal Board Book for Babies and Toddlers this Christmas (Punderland)',
       'I Love You to the Moon and Back',
       "I'm Dead, Now What?: Important Information About My Belongings, Business Affairs, and Wishes",
       'If Animals Kissed Good Night',
       'Interesting Facts For Curious Minds: 1572 Random But Mind-Blowing Facts About History, Science, Pop Culture And Everything In Between',
       'Israel: A Simple Guide to the Most Misunderstood Country on Earth',
       'Just Because',
       'Killers of the Flower Moon: The Osage Murders and the Birth of the FBI',
       'Lessons in Chemistry: A Novel',
       "Little Blue Truck's Christmas: A Christmas Holiday Book for Kids",
       'Llama Llama Gives Thanks', 'Moo, Baa, La La La!',
       'My First Library : Boxset of 10 Board Books for Kids (My First Book of)',
       'Night (Night)', 'No Brainer (Diary of a Wimpy Kid Book 18)',
       'Outlive: The Science and Art of Longevity',
       'Paint by Sticker Kids: Christmas: Create 10 Pictures One Sticker at a Time! Includes Glitter Stickers',
       'Paw Patrol Phonics: 12 Books in 1',
       'Percy Jackson and the Olympians: The Chalice of the Gods (Percy Jackson & the Olympians)',
       "Pookie's Thanksgiving (Little Pookie)",
       'Remarkably Bright Creatures: A Read with Jenna Pick',
       'Rich Dad Poor Dad: What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!',
       'School Zone - Multiplication 0-12 Flash Cards - Ages 8+, 3rd Grade, 4th Grade, Elementary Math, Multiplication Facts, Common Core, and More',
       "Stocking Stuffer Mad Libs: World's Greatest Word Game",
       'Taylor Swift: A Little Golden Book Biography',
       'The 48 Laws of Power',
       'The Ballad of Songbirds and Snakes (A Hunger Games Novel) (The Hunger Games)',
       'The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma',
       'The Christmas Fix',
       "The Complete Cookbook for Young Chefs: 100+ Recipes that You'll Love to Cook and Eat",
       "The Covenant of Water (Oprah's Book Club)", 'The Coworker',
       'The Creative Act: A Way of Being',
       'The Exchange: After The Firm (The Firm Series)',
       'The Four Agreements: A Practical Guide to Personal Freedom (A Toltec Wisdom Book)',
       'The Great Disappearance: 31 Ways to be Rapture Ready',
       'The Housemaid',
       'The Leaf Thief: (The Perfect Fall Book for Children and Toddlers)',
       'The Psychology of Money: Timeless lessons on wealth, greed, and happiness',
       'The Seven Husbands of Evelyn Hugo: A Novel',
       'The Shadow Work Journal 2nd Edition: a Guide to Integrate and Transcend Your Shadows: The Essential Guidebook for Shadow Work',
       'The Shadow Work Journal: A Guide to Integrate and Transcend your Shadows',
       'The Very Hungry Caterpillar',
       'The Wager: A Tale of Shipwreck, Mutiny and Murder',
       'The Woman in Me', 'The Wonderful Things You Will Be',
       'The Wonky Donkey',
       'There Was an Old Lady Who Swallowed a Turkey!',
       'Things We Never Got Over (Knockemout)',
       "Tom Lake: A Reese's Book Club Pick", 'Turkey Trouble', 'Verity',
       "Where's Bluey?: A Search-and-Find Book", "Where's Spot?",
       'World of Eric Carle, Around the Farm 30-Button Animal Sound Book - Great for First Words - PI Kids'],
      dtype=object)

In [22]:
sales_df = pd.read_csv('data/cleaned_bestsellers_approximated_sales.csv')

In [29]:
sales_df.book_title.unique()

array(['A Tale of Two Cities', 'The Little Prince (Le Petit Prince)',
       'The Alchemist (O Alquimista)',
       "Harry Potter and the Philosopher's Stone",
       'And Then There Were None', 'Dream of the Red Chamber (紅樓夢)',
       'The Hobbit', "Alice's Adventures in Wonderland",
       'The Lion, the Witch and the Wardrobe',
       'She: A History of Adventure', 'The Da Vinci Code',
       'Harry Potter and the Chamber of Secrets',
       'The Catcher in the Rye',
       'Harry Potter and the Prisoner of Azkaban',
       'Harry Potter and the Goblet of Fire',
       'Harry Potter and the Order of Phoenix',
       'Harry Potter and the Half-Blood Prince',
       'Harry Potter and the Deathly Hallows',
       'The Bridges of Madison County',
       'One Hundred Years of Solitude (Cien años de soledad)', 'Lolita',
       'Heidi', 'The Common Sense Book of Baby and Child Care',
       'Anne of Green Gables', 'Black Beauty',
       'The Name of the Rose (Il Nome della Rosa)',
       'The Eagle Has Landed', 'Watership Down', 'The Hite Report',
       "Charlotte's Web", 'The Ginger Man', 'The Tale of Peter Rabbit',
       'Jonathan Livingston Seagull', 'The Very Hungry Caterpillar',
       'A Message to Garcia', 'To Kill a Mockingbird',
       'Flowers in the Attic', 'Cosmos', "Sophie's World (Sofies verden)",
       'Angels & Demons', 'Alcoholics Anonymous', 'Kane and Abel',
       'How the Steel Was Tempered (Как закалялась сталь)',
       'War and Peace (Война и мир)',
       'The Adventures of Pinocchio (Le avventure di Pinocchio)',
       'The Diary of Anne Frank (Het Achterhuis)', 'Your Erroneous Zones',
       'The Thorn Birds', 'The Kite Runner', 'Valley of the Dolls',
       'How to Win Friends and Influence People', 'The Great Gatsby',
       'Gone with the Wind', 'Rebecca', 'The Revolt of Mamie Stover',
       'The Girl with the Dragon Tattoo (Män som hatar kvinnor)',
       'The Lost Symbol', 'The Hunger Games', 'James and the Giant Peach',
       'The Young Guard (Молодая гвардия)', 'Who Moved My Cheese?',
       'A Brief History of Time', 'Paul et Virginie', 'Lust for Life',
       'The Wind in the Willows',
       'The 7 Habits of Highly Effective People',
       'Totto-Chan: The Little Girl at the Window (窓ぎわのトットちゃん)',
       'Virgin Soil Upturned (Поднятая целина)', 'The Celestine Prophecy',
       'The Fault in Our Stars', 'The Girl on the Train', 'The Shack',
       'Uncle Styopa (Дядя Стёпа)', 'The Godfather', 'Love Story',
       'Catching Fire', 'Mockingjay', 'Kitchen (キッチン)',
       'Andromeda Nebula (Туманность Андромеды)', 'Gone Girl',
       'The Bermuda Triangle', 'Things Fall Apart', 'Wolf Totem (狼图腾)',
       'The Happy Hooker: My Own Story', 'Jaws', 'Love You Forever',
       "The Women's Room", "What to Expect When You're Expecting",
       'Adventures of Huckleberry Finn',
       'The Secret Diary of Adrian Mole, Aged 13¾', 'Pride and Prejudice',
       'Kon-Tiki: Across the Pacific in a Raft (Kon-Tiki ekspedisjonen)',
       'The Good Soldier Švejk (Osudy dobrého vojáka Švejka za světové války)',
       'Where the Wild Things Are', 'The Power of Positive Thinking',
       'The Secret', 'Fear of Flying', 'Dune',
       'Charlie and the Chocolate Factory', 'The Naked Ape',
       'Kokoro (こゝろ)'], dtype=object)

In [28]:
# TODO: normalize titles

In [33]:
# Normalize the book titles
sales_df['normalized_title'] = sales_df['book_title'].str.split('(').str[0].str.strip().str.lower()

In [35]:
# Normalize the book titles
merged_df['normalized_title'] = merged_df['book_name'].str.split('(').str[0].str.strip().str.lower()

In [54]:
merged_df['is_successful'] = merged_df['normalized_title'].isin(sales_df['normalized_title'])

In [56]:
merged_df.is_successful.unique()

array([False,  True])

In [57]:
merged_df[merged_df.is_successful]

,book_name,positive_count,total_count,positive_percentage,normalized_title,is_successful
24,Harry Potter and the Prisoner of Azkaban (Harr...,10,10,100.0,harry potter and the prisoner of azkaban,True
78,The Very Hungry Caterpillar,10,10,100.0,the very hungry caterpillar,True

In [58]:
# Step 1: Filter to include only positive reviews
positive_reviews_predicted = data[data['sentiment_given'] == 'positive']

# Step 2: Group by title to get the count of positive reviews per book
positive_count = positive_reviews_predicted.groupby('book_name').size().reset_index(name='positive_count')

# Step 3: Group the entire dataset by title to get the total count of reviews per book
total_count = data.groupby('book_name').size().reset_index(name='total_count')

# Step 4: Merge the positive count and total count DataFrames
merged_df_predicted = pd.merge(positive_count, total_count, on='book_name')

# Step 5: Calculate the percentage of positive reviews
merged_df_predicted['positive_percentage'] = (merged_df_predicted['positive_count'] / merged_df_predicted['total_count']) * 100

In [59]:
# Display the result
merged_df_predicted

,book_name,positive_count,total_count,positive_percentage
0,A Court of Mist and Fury (A Court of Thorns an...,10,10,100.0
1,A Court of Thorns and Roses (A Court of Thorns...,8,10,80.0
2,A Court of Thorns and Roses Paperback Box Set ...,10,10,100.0
3,A Court of Wings and Ruin (A Court of Thorns a...,9,10,90.0
4,A Little Life,10,10,100.0
...,...,...,...,...
86,Turkey Trouble,10,10,100.0
87,Verity,10,10,100.0
88,Where's Bluey?: A Search-and-Find Book,10,10,100.0
89,Where's Spot?,10,10,100.0
90,"World of Eric Carle, Around the Farm 30-Button...",10,10,100.0

In [60]:
# Normalize the book titles
merged_df_predicted['normalized_title'] = merged_df_predicted['book_name'].str.split('(').str[0].str.strip().str.lower()

In [61]:
merged_df_predicted['is_successful'] = merged_df_predicted['normalized_title'].isin(sales_df['normalized_title'])

In [62]:
merged_df_predicted[merged_df.is_successful]

,book_name,positive_count,total_count,positive_percentage,normalized_title,is_successful
24,Harry Potter and the Prisoner of Azkaban (Harr...,10,10,100.0,harry potter and the prisoner of azkaban,True
78,The Very Hungry Caterpillar,10,10,100.0,the very hungry caterpillar,True

In [66]:
data[(data.book_name.str.contains('Harry Potter and the Prisoner of Azkaban')) |
data.book_name.str.contains('The Very Hungry Caterpillar')]

,#,book_name,reviewer_anonymous,reviewer_rating,review_description,date,sentiment_given,sentiment_predicted
290,290,The Very Hungry Caterpillar,cf87a8289eeb0944ddd75a6457337e18b6925ad3f3f9e1...,5,The media could not be loaded. Where to even b...,04-09-2023,positive,positive
291,291,The Very Hungry Caterpillar,f537e53d930ce002e378cd0e503006effd1a3dadbe653a...,5,Every child’s library whether public or in the...,29-10-2023,positive,positive
292,292,The Very Hungry Caterpillar,7fb95f790d96769e5bf94be567ac03f174214d54f459a8...,5,"Cute story, colorful illustrations, and perfec...",06-11-2023,positive,positive
293,293,The Very Hungry Caterpillar,f5ea3614e396c1bf0c6ebd301a2d7b2f4b23dd26233c1e...,5,Books are my favorite gift to first-time paren...,16-10-2023,positive,positive
294,294,The Very Hungry Caterpillar,62de695c93b80996d0d5c8053c51e6220b60f5d48a3525...,5,"This story creates belly laughs, such fun and ...",25-10-2023,positive,positive
295,295,The Very Hungry Caterpillar,4d08697ada75dc79d8f4a9193efb19d01d3609928411d5...,5,"This book has been around for decades, got it ...",23-10-2023,positive,positive
296,296,The Very Hungry Caterpillar,d5ef996639091278315e21f37b279ee9f2556b49f2c2f7...,4,My little one doesn’t enjoy this book as much ...,03-11-2023,positive,positive
297,297,The Very Hungry Caterpillar,b211d529848e97e39921a1cfa942738bb5388763a19348...,5,Loved this book as a kid and It means a lot to...,18-10-2023,positive,positive
298,298,The Very Hungry Caterpillar,0b8d6362ab499eee931c70ea9bc1e48266688444ed5c03...,5,CLASSIC WONDERFULLY BOOK.,29-10-2023,positive,positive
299,299,The Very Hungry Caterpillar,1626883801c4fe49d1a7073924d0f63542e09fe5bb99ea...,5,This is a great book for children. The colors ...,18-10-2023,positive,positive
807,810,Harry Potter and the Prisoner of Azkaban (Harr...,cf5cbc3e69e067bfe5d54103853a398118399508f490b7...,5,"As a lifelong Harry Potter superfan, I was so ...",31-10-2023,positive,positive
808,811,Harry Potter and the Prisoner of Azkaban (Harr...,8145f2ff015f6a1e8275cf3d6fd70f770f6d80b3378283...,5,I already owned the entire series in a nice ha...,26-10-2023,positive,positive
809,812,Harry Potter and the Prisoner of Azkaban (Harr...,2d0bccb924b950ae845fd5bff0fd80bca9efeeb999e3b0...,5,Minalima's interactive papercraft is always be...,07-10-2023,positive,positive
810,813,Harry Potter and the Prisoner of Azkaban (Harr...,429485263fda9049270a09f3e8c23f51bd09b0e5e3213b...,5,"First off, another Mina Lima edition. These ar...",21-10-2023,positive,positive
811,814,Harry Potter and the Prisoner of Azkaban (Harr...,b9a3d69887684824a64d9a9256e337630f4d1ef4b291df...,5,Was so excited to get this next book in the se...,02-11-2023,positive,positive
812,815,Harry Potter and the Prisoner of Azkaban (Harr...,7ef13e568325127883aab0dc5b73cff459984edc9b420e...,5,Love these editions. The art style is perfect ...,24-10-2023,positive,positive
813,816,Harry Potter and the Prisoner of Azkaban (Harr...,f4b24fed0274a31618ac1b665ee162af331b4b70fdff74...,5,I'm a happy camper such beautiful well thought...,15-10-2023,positive,positive
814,817,Harry Potter and the Prisoner of Azkaban (Harr...,201d6edc5324ee6e230e37d4a90e5c9cf95c7ab85ec729...,5,I always look forward to these books coming ou...,09-10-2023,positive,positive
815,818,Harry Potter and the Prisoner of Azkaban (Harr...,ac3fee6b14325f68b25d89e88ada73ace6961dcb5f8c15...,5,Minalima did it again! I pre-ordered this and ...,01-11-2023,positive,positive
816,819,Harry Potter and the Prisoner of Azkaban (Harr...,6cf4bd58f959371f0d52a651932a9b44be7df6d355edbd...,5,These editions of Harry Potter are our absolut...,02-11-2023,positive,positive

In [67]:
merged_df_predicted.to_csv('data/sales_success_data.csv')